---
title: "day5a"
format: html
execute:
  warning: false
---

```{r, include=FALSE}

library(tidyverse)

```

```{r}
head(starwars)

tail(starwars)

dim(starwars)

view(starwars)
```


```{r, echo= FALSE, fig.cap="A scatterplot of height and mass of StarWars characters"}
ggplot(starwars, aes(height, mass, color = gender)) +
  geom_point() +
  labs(x = "Height (cm)",
       y = "Mass (kg)") +
  scale_color_manual(values = c("lightpink", "darkblue", "palegreen"))

```

```{r, echo= FALSE}
ggplot(starwars, aes(x = height)) +
  geom_histogram(color = "white", fill = "lightblue")

```

```{r}
starwars$height
```

```{r}
sw_height_mean <- round(mean(starwars$height, na.rm = TRUE), 1)

sw_height_mean
```

```{r}
sw_height_median <- median(starwars$height, na.rm = TRUE)

sw_height_median

```
```{r}
sw_height_variance <- var(starwars$height, na.rm = TRUE)

sw_height_sd <- sd(starwars$height, na.rm = TRUE)

sw_height_variance


sw_height_sd
```

The mean height of the characters in Star Wars is `r sw_height_mean` cm.
